/**
 * seeds/vehicles.js — Single source of truth for initial vehicle seed data.
 *
 * Previously duplicated in: server/index.js, server/memoryDb.js, client/src/App.jsx
 * Now lives only here. All references must import from this file.
 */

export const seedVehicles = [
  {
    vehicleId: 'VEH-00001',
    name: 'Mahindra Thar 4x4',
    brand: 'Mahindra',
    regNumber: 'MP-09-WX-9999',
    category: 'Car',
    fuelType: 'Diesel',
    seatingCapacity: 4,
    color: 'Napoli Black',
    meterReading: 1200,
    fuelCapacity: 57,
    mileage: 15,
    description: 'Premium adventure 4x4 SUV',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 150, freeKm: 5, fuelChargePerKm: 5, extraKmCharge: 12, withFuel: 200, withoutFuel: 150 },
      twelveHour: { baseRate: 1200, ratePerHour: 100, kmLimit: 120, fuelChargePerKm: 5, extraKmCharge: 12, extraHourCharge: 120, gracePeriod: 30, withFuel: 1800, withoutFuel: 1200 },
      twentyFourHour: { baseRate: 2000, ratePerHour: 80, kmLimit: 250, fuelChargePerKm: 5, extraKmCharge: 12, extraHourCharge: 100, gracePeriod: 60, withFuel: 3000, withoutFuel: 2000 },
      weekly: { baseRate: 12000, kmLimit: 1500, extraKmCharge: 10, extraDayCharge: 2000, gracePeriod: 120 },
      monthly: { baseRate: 35000, kmLimit: 5000, extraKmCharge: 8, extraDayCharge: 1500 }
    },
    depositSettings: { requireDeposit: true, amount: 5000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['UPI', 'Cash', 'Card'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Vijay Nagar', currentBranch: 'Vijay Nagar Branch', parkingLocation: 'Slot T-1' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00002',
    name: 'Honda Activa 6G',
    brand: 'Honda',
    regNumber: 'MP-09-AB-1234',
    category: 'Scooty',
    fuelType: 'Petrol',
    seatingCapacity: 2,
    color: 'Matte Blue',
    meterReading: 15400,
    fuelCapacity: 5.3,
    mileage: 45,
    description: 'Comfortable family scooty',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 50, freeKm: 5, fuelChargePerKm: 2, extraKmCharge: 5, withFuel: 60, withoutFuel: 50 },
      twelveHour: { baseRate: 350, ratePerHour: 40, kmLimit: 60, fuelChargePerKm: 2, extraKmCharge: 5, extraHourCharge: 40, gracePeriod: 15, withFuel: 450, withoutFuel: 350 },
      twentyFourHour: { baseRate: 500, ratePerHour: 30, kmLimit: 120, fuelChargePerKm: 2, extraKmCharge: 5, extraHourCharge: 30, gracePeriod: 30, withFuel: 650, withoutFuel: 500 },
      weekly: { baseRate: 3000, kmLimit: 800, extraKmCharge: 4, extraDayCharge: 500, gracePeriod: 60 },
      monthly: { baseRate: 9000, kmLimit: 3000, extraKmCharge: 3, extraDayCharge: 400 }
    },
    depositSettings: { requireDeposit: true, amount: 1000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['Cash', 'UPI'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Vijay Nagar', currentBranch: 'Vijay Nagar Branch', parkingLocation: 'Slot B-3' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00003',
    name: 'Royal Enfield Classic 350',
    brand: 'Royal Enfield',
    regNumber: 'MP-09-RE-3500',
    category: 'Bike',
    fuelType: 'Petrol',
    seatingCapacity: 2,
    color: 'Stealth Black',
    meterReading: 8200,
    fuelCapacity: 13.5,
    mileage: 35,
    description: 'Iconic retro cruiser motorcycle',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 80, freeKm: 5, fuelChargePerKm: 3, extraKmCharge: 8, withFuel: 100, withoutFuel: 80 },
      twelveHour: { baseRate: 600, ratePerHour: 60, kmLimit: 100, fuelChargePerKm: 3, extraKmCharge: 8, extraHourCharge: 60, gracePeriod: 20, withFuel: 800, withoutFuel: 600 },
      twentyFourHour: { baseRate: 1000, ratePerHour: 50, kmLimit: 200, fuelChargePerKm: 3, extraKmCharge: 8, extraHourCharge: 50, gracePeriod: 30, withFuel: 1300, withoutFuel: 1000 },
      weekly: { baseRate: 6000, kmLimit: 1200, extraKmCharge: 6, extraDayCharge: 1000, gracePeriod: 60 },
      monthly: { baseRate: 18000, kmLimit: 4000, extraKmCharge: 5, extraDayCharge: 800 }
    },
    depositSettings: { requireDeposit: true, amount: 2000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['Cash', 'UPI', 'Card'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Vijay Nagar', currentBranch: 'Vijay Nagar Branch', parkingLocation: 'Slot B-7' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00004',
    name: 'Maruti Suzuki Swift',
    brand: 'Maruti',
    regNumber: 'MP-09-AB-4444',
    category: 'Car',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    color: 'Solid Fire Red',
    meterReading: 8500,
    fuelCapacity: 37,
    mileage: 22,
    description: 'Popular compact hatchback',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 100, freeKm: 5, fuelChargePerKm: 4, extraKmCharge: 8, withFuel: 150, withoutFuel: 100 },
      twelveHour: { baseRate: 800, ratePerHour: 80, kmLimit: 120, fuelChargePerKm: 4, extraKmCharge: 8, extraHourCharge: 80, gracePeriod: 30, withFuel: 1300, withoutFuel: 800 },
      twentyFourHour: { baseRate: 1500, ratePerHour: 60, kmLimit: 250, fuelChargePerKm: 4, extraKmCharge: 8, extraHourCharge: 60, gracePeriod: 60, withFuel: 2500, withoutFuel: 1500 },
      weekly: { baseRate: 9000, kmLimit: 1500, extraKmCharge: 7, extraDayCharge: 1500, gracePeriod: 120 },
      monthly: { baseRate: 25000, kmLimit: 5000, extraKmCharge: 6, extraDayCharge: 1200 }
    },
    depositSettings: { requireDeposit: true, amount: 3000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['UPI', 'Cash', 'Card'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Vijay Nagar', currentBranch: 'Vijay Nagar Branch', parkingLocation: 'Slot T-2' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00005',
    name: 'Hyundai i20 Asta',
    brand: 'Hyundai',
    regNumber: 'MP-09-CD-5555',
    category: 'Car',
    fuelType: 'Petrol',
    seatingCapacity: 5,
    color: 'Polar White',
    meterReading: 12400,
    fuelCapacity: 37,
    mileage: 18,
    description: 'Premium family hatchback',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 120, freeKm: 5, fuelChargePerKm: 4, extraKmCharge: 10, withFuel: 180, withoutFuel: 120 },
      twelveHour: { baseRate: 1000, ratePerHour: 90, kmLimit: 120, fuelChargePerKm: 4, extraKmCharge: 10, extraHourCharge: 90, gracePeriod: 30, withFuel: 1500, withoutFuel: 1000 },
      twentyFourHour: { baseRate: 1800, ratePerHour: 70, kmLimit: 250, fuelChargePerKm: 4, extraKmCharge: 10, extraHourCharge: 70, gracePeriod: 60, withFuel: 2800, withoutFuel: 1800 },
      weekly: { baseRate: 10500, kmLimit: 1500, extraKmCharge: 8, extraDayCharge: 1800, gracePeriod: 120 },
      monthly: { baseRate: 30000, kmLimit: 5000, extraKmCharge: 7, extraDayCharge: 1400 }
    },
    depositSettings: { requireDeposit: true, amount: 4000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['UPI', 'Cash', 'Card'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Vijay Nagar', currentBranch: 'Vijay Nagar Branch', parkingLocation: 'Slot T-3' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00006',
    name: 'Toyota Fortuner Sigma4',
    brand: 'Toyota',
    regNumber: 'MP-09-EF-6666',
    category: 'Car',
    fuelType: 'Diesel',
    seatingCapacity: 7,
    color: 'Super White',
    meterReading: 45000,
    fuelCapacity: 80,
    mileage: 10,
    description: 'Elite luxury 7-seater SUV',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 300, freeKm: 5, fuelChargePerKm: 8, extraKmCharge: 20, withFuel: 400, withoutFuel: 300 },
      twelveHour: { baseRate: 2500, ratePerHour: 200, kmLimit: 120, fuelChargePerKm: 8, extraKmCharge: 20, extraHourCharge: 200, gracePeriod: 30, withFuel: 3500, withoutFuel: 2500 },
      twentyFourHour: { baseRate: 4500, ratePerHour: 180, kmLimit: 250, fuelChargePerKm: 8, extraKmCharge: 20, extraHourCharge: 180, gracePeriod: 60, withFuel: 6500, withoutFuel: 4500 },
      weekly: { baseRate: 28000, kmLimit: 1500, extraKmCharge: 15, extraDayCharge: 4500, gracePeriod: 120 },
      monthly: { baseRate: 85000, kmLimit: 5000, extraKmCharge: 12, extraDayCharge: 3500 }
    },
    depositSettings: { requireDeposit: true, amount: 10000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['UPI', 'Cash', 'Card'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Palasia', currentBranch: 'Palasia Branch', parkingLocation: 'Slot P-1' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00007',
    name: 'TVS Jupiter 125',
    brand: 'TVS',
    regNumber: 'MP-09-GH-7777',
    category: 'Scooty',
    fuelType: 'Petrol',
    seatingCapacity: 2,
    color: 'Titanium Grey',
    meterReading: 22000,
    fuelCapacity: 6,
    mileage: 50,
    description: 'Spacious and comfortable family scooter',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 45, freeKm: 5, fuelChargePerKm: 2, extraKmCharge: 5, withFuel: 55, withoutFuel: 45 },
      twelveHour: { baseRate: 300, ratePerHour: 35, kmLimit: 60, fuelChargePerKm: 2, extraKmCharge: 5, extraHourCharge: 35, gracePeriod: 15, withFuel: 400, withoutFuel: 300 },
      twentyFourHour: { baseRate: 450, ratePerHour: 25, kmLimit: 120, fuelChargePerKm: 2, extraKmCharge: 5, extraHourCharge: 25, gracePeriod: 30, withFuel: 600, withoutFuel: 450 },
      weekly: { baseRate: 2500, kmLimit: 800, extraKmCharge: 4, extraDayCharge: 400, gracePeriod: 60 },
      monthly: { baseRate: 8000, kmLimit: 3000, extraKmCharge: 3, extraDayCharge: 300 }
    },
    depositSettings: { requireDeposit: true, amount: 1000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['Cash', 'UPI'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Vijay Nagar', currentBranch: 'Vijay Nagar Branch', parkingLocation: 'Slot B-4' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00008',
    name: 'Ola S1 Pro Gen 2',
    brand: 'Ola',
    regNumber: 'MP-09-IJ-8888',
    category: 'Scooty',
    fuelType: 'Electric',
    seatingCapacity: 2,
    color: 'Midnight Blue',
    meterReading: 5100,
    fuelCapacity: 4,
    mileage: 130,
    description: 'High performance electric scooter',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 60, freeKm: 5, fuelChargePerKm: 0, extraKmCharge: 5, withFuel: 60, withoutFuel: 60 },
      twelveHour: { baseRate: 400, ratePerHour: 40, kmLimit: 70, fuelChargePerKm: 0, extraKmCharge: 5, extraHourCharge: 40, gracePeriod: 15, withFuel: 400, withoutFuel: 400 },
      twentyFourHour: { baseRate: 600, ratePerHour: 30, kmLimit: 140, fuelChargePerKm: 0, extraKmCharge: 5, extraHourCharge: 30, gracePeriod: 30, withFuel: 600, withoutFuel: 600 },
      weekly: { baseRate: 3500, kmLimit: 900, extraKmCharge: 4, extraDayCharge: 600, gracePeriod: 60 },
      monthly: { baseRate: 11000, kmLimit: 3500, extraKmCharge: 3, extraDayCharge: 500 }
    },
    depositSettings: { requireDeposit: true, amount: 1500 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['Cash', 'UPI'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Bhawarkua', currentBranch: 'Bhawarkua Branch', parkingLocation: 'Slot EV-1' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00009',
    name: 'Yamaha YZF R15 V4',
    brand: 'Yamaha',
    regNumber: 'MP-09-KL-9999',
    category: 'Bike',
    fuelType: 'Petrol',
    seatingCapacity: 2,
    color: 'Racing Blue',
    meterReading: 11200,
    fuelCapacity: 11,
    mileage: 40,
    description: 'Track-focused sports motorcycle',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 100, freeKm: 5, fuelChargePerKm: 3, extraKmCharge: 8, withFuel: 120, withoutFuel: 100 },
      twelveHour: { baseRate: 700, ratePerHour: 70, kmLimit: 100, fuelChargePerKm: 3, extraKmCharge: 8, extraHourCharge: 70, gracePeriod: 20, withFuel: 900, withoutFuel: 700 },
      twentyFourHour: { baseRate: 1200, ratePerHour: 60, kmLimit: 200, fuelChargePerKm: 3, extraKmCharge: 8, extraHourCharge: 60, gracePeriod: 30, withFuel: 1500, withoutFuel: 1200 },
      weekly: { baseRate: 7500, kmLimit: 1200, extraKmCharge: 6, extraDayCharge: 1200, gracePeriod: 60 },
      monthly: { baseRate: 22000, kmLimit: 4000, extraKmCharge: 5, extraDayCharge: 1000 }
    },
    depositSettings: { requireDeposit: true, amount: 3000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['Cash', 'UPI', 'Card'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Vijay Nagar', currentBranch: 'Vijay Nagar Branch', parkingLocation: 'Slot B-8' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  },
  {
    vehicleId: 'VEH-00010',
    name: 'KTM Duke 390 ABS',
    brand: 'KTM',
    regNumber: 'MP-09-MN-0000',
    category: 'Bike',
    fuelType: 'Petrol',
    seatingCapacity: 2,
    color: 'Ceramic White',
    meterReading: 6800,
    fuelCapacity: 13.4,
    mileage: 28,
    description: 'Powerful naked street fighter bike',
    status: 'Available',
    pricingPlans: {
      hourly: { rate: 120, freeKm: 5, fuelChargePerKm: 4, extraKmCharge: 10, withFuel: 150, withoutFuel: 120 },
      twelveHour: { baseRate: 900, ratePerHour: 80, kmLimit: 100, fuelChargePerKm: 4, extraKmCharge: 10, extraHourCharge: 80, gracePeriod: 20, withFuel: 1100, withoutFuel: 900 },
      twentyFourHour: { baseRate: 1500, ratePerHour: 70, kmLimit: 200, fuelChargePerKm: 4, extraKmCharge: 10, extraHourCharge: 70, gracePeriod: 30, withFuel: 1900, withoutFuel: 1500 },
      weekly: { baseRate: 9000, kmLimit: 1200, extraKmCharge: 8, extraDayCharge: 1500, gracePeriod: 60 },
      monthly: { baseRate: 28000, kmLimit: 4000, extraKmCharge: 7, extraDayCharge: 1200 }
    },
    depositSettings: { requireDeposit: true, amount: 5000 },
    paymentSettings: { advanceRequired: true, percentage: 50, acceptedModes: ['Cash', 'UPI', 'Card'] },
    bookingConfig: { bufferTime: 30, status: 'Active', bookingEnabled: true, instantBooking: true },
    locationDetails: { currentZone: 'Palasia', currentBranch: 'Palasia Branch', parkingLocation: 'Slot B-9' },
    documents: { rcUrl: '', insuranceUrl: '', pucUrl: '', fitnessUrl: '' },
    images: { front: '', back: '', left: '', right: '', interior: '', document: '', other: '' },
    availability: { availableForBooking: true, reason: '' },
    maintenanceRecords: [],
    auditLogs: [],
    assignedWorker: 'Ramesh Kumar'
  }
];
